#ifndef GUID_LOOKUP_H
#define GUID_LOOKUP_H

#include <windows.h>
#include <guiddef.h>

// The structure representing a GUID entry in the hash table
struct GuidLookup {
    const char* guid; // String representation of the GUID
    const char* name;
};

// The function generated by gperf for GUID lookup
struct GuidLookup* in_word_set(const GUID* guid);
#endif // GUID_LOOKUP_H
